### PR TITLE
Lint and typecheck generated templates during CI testing

### PR DESCRIPTION
**Pull request by AlCalzone**
**PR Checklist:**

-   [x] Provide a meaningful description to this PR or mention which issues this fixes.
-   [x] Add tests for your change. This includes negative tests (i.e. inputs that need to fail) as well as baseline tests (i.e. how should the directory structure look like?).
-   [x] Run the test suite with `npm test`
-   [x] If there are baseline changes, review them and make a separate commit for them with the comment "accept baselines" if they are desired changes
-   [x] Ensure the project builds with `npm run build`
-   [ ] ~~If you added a required option, also add it to the template creation (`.github/create_templates.ts`)~~ not applicable
-   [ ] ~~Add a detailed migration description to `docs/updates` explaining what the user needs to do when manually updating an existing project~~ This change is not user-facing
-   [x] Add your changes to `CHANGELOG.md` (referencing the migration description and this PR or the issue you fixed)

**Description:**  
With this PR, we now run ESLint and tsc on the generated templates (the ones that go into the `ioBroker.template` repo). Since they cover the most use cases, this allows us to catch any style problems or bugs in the output.

### CODE REVIEW

**Comment by AlCalzone** [comment]
This PR includes the changes from #609 so best start reviewing after c25e0d0

**Comment by AlCalzone** [comment]
@UncleSamSwiss please review :)

**Review by UncleSamSwiss — APPROVED** [review]
Looks good. Did you test it with a broken file?

Edit: found it :-)
This is an example of failing tests: https://github.com/ioBroker/create-adapter/pull/610/checks?check_run_id=1321084155

**Comment by AlCalzone** [comment]
Yeah, I didn't have to create one, this branch started with a bunch of broken files :D

**Pull request merged**
