### PR TITLE
CSS fix for React UI in Firefox browser

### PR DESCRIPTION
**Pull request by crycode-de**
**PR Checklist:**

-   [x] Provide a meaningful description to this PR or mention which issues this fixes.
-   [ ] ~Add tests for your change. This includes negative tests (i.e. inputs that need to fail) as well as baseline tests (i.e. how should the directory structure look like?).~
-   [x] Run the test suite with `npm test`
-   [ ] ~If there are baseline changes, review them and make a separate commit for them with the comment "accept baselines" if they are desired changes~
-   [x] Ensure the project builds with `npm run build`
-   [ ] ~If you added a required option, also add it to the template creation (`.github/create_templates.ts`)~
-   [x] Add a detailed migration description to `docs/updates` explaining what the user needs to do when manually updating an existing project
-   [x] Add your changes to `CHANGELOG.md` (referencing the migration description and this PR or the issue you fixed)

**Description:**  
This will fix a display bug in Firefox where the React UI does not respect the correct hight and the content overflows:
grafik

As mentioned by Bluefox in Discord each parent element should have a height set.

### CODE REVIEW

**Comment by AlCalzone** [comment]
Thanks, I'll review tonight

**Review by AlCalzone — CHANGES_REQUESTED** [review]
You ticked the box **Run the test suite with `npm test`** (which should generate new baselines) but did not include any baseline changes. These are required so we can judge the impact of the template changes. In this case it is pretty clear, but not updating them will cause these changes to be included in the next PR - which will cause confusion.

If you're unsure what to do, I can assist with that.

**Comment by crycode-de** [comment]
Didn't know that they were needed. Baseline changes are now included.

**Comment by AlCalzone** [comment]
Thanks. It seems like some of my changes got lost in the last merge 🤨
Gotta fix this later.

**Pull request merged**
