### PR TITLE
Add --jsx react to npm check script if type checking and react are used

### LINKED ISSUE #923: check-and-lint '--jsx' is not set
changing

```
    "check": "tsc --noEmit",
```

to
```
"check": "tsc --noEmit --jsx react",
```

solved the issue

WorkFlow error (using adapter create with TypeScript & React)
```
Error: admin/src/app.tsx(5,22): error TS6142: Module './components/settings' was resolved to '/home/runner/work/ioBroker.wlanthermo-nano/ioBroker.wlanthermo-nano/admin/src/components/settings.tsx', but '--jsx' is not set.
[252](https://github.com/DrozmotiX/ioBroker.wlanthermo-nano/runs/6700996590?check_suite_focus=true#step:2:264)
Error: admin/src/app.tsx(44,4): error TS17004: Cannot use JSX unless the '--jsx' flag is provided.
[253](https://github.com/DrozmotiX/ioBroker.wlanthermo-nano/runs/6700996590?check_suite_focus=true#step:2:265)
Error: admin/src/app.tsx(45,5): error TS17004: Cannot use JSX unless the '--jsx' flag is provided.
[254](https://github.com/DrozmotiX/ioBroker.wlanthermo-nano/runs/6700996590?check_suite_focus=true#step:2:266)
Error: admin/src/app.tsx(45,53): error TS7006: Parameter 'attr' implicitly has an 'any' type.
[255](https://github.com/DrozmotiX/ioBroker.wlanthermo-nano/runs/6700996590?check_suite_focus=true#step:2:267)
Error: admin/src/app.tsx(45,59): error TS7006: Parameter 'value' implicitly has an 'any' type.
[256](https://github.com/DrozmotiX/ioBroker.wlanthermo-nano/runs/6700996590?check_suite_focus=true#step:2:268)
Error: admin/src/components/settings.tsx(67,4): error TS17004: Cannot use JSX unless the '--jsx' flag is provided.
[257](https://github.com/DrozmotiX/ioBroker.wlanthermo-nano/runs/6700996590?check_suite_focus=true#step:2:269)
Error: admin/src/components/settings.tsx(85,4): error TS17004: Cannot use JSX unless the '--jsx' flag is provided.
[258](https://github.com/DrozmotiX/ioBroker.wlanthermo-nano/runs/6700996590?check_suite_focus=true#step:2:270)
Error: admin/src/components/settings.tsx(92,5): error TS17004: Cannot use JSX unless the '--jsx' flag is provided.
[259](https://github.com/DrozmotiX/ioBroker.wlanthermo-nano/runs/6700996590?check_suite_focus=true#step:2:271)
Error: admin/src/components/settings.tsx(95,13): error TS17004: Cannot use JSX unless the '--jsx' flag is provided.
[260](https://github.com/DrozmotiX/ioBroker.wlanthermo-nano/runs/6700996590?check_suite_focus=true#step:2:272)
Error: admin/src/components/settings.tsx(98,7): error TS17004: Cannot use JSX unless the '--jsx' flag is provided.
[261](https://github.com/DrozmotiX/ioBroker.wlanthermo-nano/runs/6700996590?check_suite_focus=true#step:2:273)
Error: admin/src/components/settings.tsx(103,5): error TS17004: Cannot use JSX unless the '--jsx' flag is provided.
[262](https://github.com/DrozmotiX/ioBroker.wlanthermo-nano/runs/6700996590?check_suite_focus=true#step:2:274)
Error: admin/src/components/settings.tsx(110,4): error TS17004: Cannot use JSX unless the '--jsx' flag is provided.
[263](https://github.com/DrozmotiX/ioBroker.wlanthermo-nano/runs/6700996590?check_suite_focus=true#step:2:275)
Error: admin/src/components/settings.tsx(118,6): error TS17004: Cannot use JSX unless the '--jsx' flag is provided.
[264](https://github.com/DrozmotiX/ioBroker.wlanthermo-nano/runs/6700996590?check_suite_focus=true#step:2:276)
Error: admin/src/components/settings.tsx(131,4): error TS17004: Cannot use JSX unless the '--jsx' flag is provided.
[265](https://github.com/DrozmotiX/ioBroker.wlanthermo-nano/runs/6700996590?check_suite_focus=true#step:2:277)
Error: admin/src/components/settings.tsx(133,5): error TS17004: Cannot use JSX unless the '--jsx' flag is provided.
[266](https://github.com/DrozmotiX/ioBroker.wlanthermo-nano/runs/6700996590?check_suite_focus=true#step:2:278)
Error: admin/src/index.tsx(6,17): error TS6142: Module './app' was resolved to '/home/runner/work/ioBroker.wlanthermo-nano/ioBroker.wlanthermo-nano/admin/src/app.tsx', but '--jsx' is not set.
[267](https://github.com/DrozmotiX/ioBroker.wlanthermo-nano/runs/6700996590?check_suite_focus=true#step:2:279)
Error: admin/src/index.tsx(12,3): error TS17004: Cannot use JSX unless the '--jsx' flag is provided.
[268](https://github.com/DrozmotiX/ioBroker.wlanthermo-nano/runs/6700996590?check_suite_focus=true#step:2:280)
Error: admin/src/index.tsx(13,4): error TS17004: Cannot use JSX unless the '--jsx' flag is provided.
[269](https://github.com/DrozmotiX/ioBroker.wlanthermo-nano/runs/6700996590?check_suite_focus=true#step:2:281)
Error: admin/src/index.tsx(15,21): error TS7006: Parameter '_theme' implicitly has an 'any' type.
[270](https://github.com/DrozmotiX/ioBroker.wlanthermo-nano/runs/6700996590?check_suite_focus=true#step:2:282)
npm ERR! code ELIFECYCLE
```

### PR DESCRIPTION
**Pull request by crycode-de**
**PR Checklist:**

-   [x] Provide a meaningful description to this PR or mention which issues this fixes.
-   [ ] ~~Add tests for your change. This includes negative tests (i.e. inputs that need to fail) as well as baseline tests (i.e. how should the directory structure look like?).~~
-   [x] Run the test suite with `npm test`
-   [x] If there are baseline changes, review them and make a separate commit for them with the comment "accept baselines" if they are desired changes
-   [x] Ensure the project builds with `npm run build`
-   [ ] ~~If you added a required option, also add it to the template creation (`.github/create_templates.ts`)~~
-   [x] Add a detailed migration description to `docs/updates` explaining what the user needs to do when manually updating an existing project
-   [x] Add your changes to `CHANGELOG.md` (referencing the migration description and this PR or the issue you fixed)

**Description:**  

~~If type checking and react are used, the npm script "check" needs the option `--jsx react`.
Otherwise check will fail with `error TS17004: Cannot use JSX unless the '--jsx' flag is provided.`~~

Check TS-React code using separate tsconfig files for src and admin.
The npm script _check_ needs to run two checks with the associated tsconfig files for adapter src and admin src separately.
Otherwise the check will fail with `error TS17004: Cannot use JSX unless the '--jsx' flag is provided`.

Fixes #923

### CODE REVIEW

**Review by AlCalzone — CHANGES_REQUESTED** [review]
I think we're just missing this option in one of the tsconfigs. Having to specify it on the CLI seems weird.

**Comment by AlCalzone** [comment]
So I just double checked my adapters. IMO we should remove the admin dir from the root `tsconfig` for TS-React:
https://github.com/ioBroker/create-adapter/blob/72a025eac65291149399d5d9d35e446c659896d4/templates/tsconfig.json.ts#L53-L54
and instead do two check runs, one in the root dir and one with `tsc --noEmit && tsc --noEmit -p admin/tsconfig.json`

**Comment by AlCalzone** [comment]
Hmm looks like ESLint now needs a separate tsconfig that includes both directories again:
```
> eslint --ext .ts,.tsx src/ admin/src/
/home/runner/work/create-adapter/create-adapter/.github/ioBroker.template/TypeScriptReact/admin/src/app.tsx
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: admin/src/app.tsx.
The file must be included in at least one of the projects provided
/home/runner/work/create-adapter/create-adapter/.github/ioBroker.template/TypeScriptReact/admin/src/components/settings.tsx
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: admin/src/components/settings.tsx.
The file must be included in at least one of the projects provided
/home/runner/work/create-adapter/create-adapter/.github/ioBroker.template/TypeScriptReact/admin/src/i18n/i18n.d.ts
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: admin/src/i18n/i18n.d.ts.
The file must be included in at least one of the projects provided
/home/runner/work/create-adapter/create-adapter/.github/ioBroker.template/TypeScriptReact/admin/src/index.tsx
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: admin/src/index.tsx.
The file must be included in at least one of the projects provided
/home/runner/work/create-adapter/create-adapter/.github/ioBroker.template/TypeScriptReact/admin/src/tab-app.tsx
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: admin/src/tab-app.tsx.
The file must be included in at least one of the projects provided
/home/runner/work/create-adapter/create-adapter/.github/ioBroker.template/TypeScriptReact/admin/src/tab.tsx
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: admin/src/tab.tsx.
The file must be included in at least one of the projects provided
✖ 6 problems (6 errors, 0 warnings)
```

**Comment by AlCalzone** [comment]
Or we go back to one check run and move the `jsx` flag into the root tsconfig?
@UncleSamSwiss ?

**Comment by crycode-de** [comment]
> Hmm looks like ESLint now needs a separate tsconfig that includes both directories again:

Should be fixed now by setting both tsconfig files in the eslint config ;)

**Review by AlCalzone — COMMENTED** [review]
I'm not sure we need to exclude `admin/` in the root `tsconfig` since it is not included. The rest looks fine. @UncleSamSwiss what do you think?

**Comment by crycode-de** [comment]
For some reason I had to exclude `admin/` in the root tsconfig of my [canbus](https://github.com/crycode-de/ioBroker.canbus/blob/master/tsconfig.json#L52) adapter. But now I don't remember exactly why...

**Comment by AlCalzone** [comment]
According to https://www.typescriptlang.org/tsconfig#exclude, `exclude` only removes files that were included using `include`, so it shouldn't really be necessary.

**Comment by crycode-de** [comment]
Anything else to do?

**Review by UncleSamSwiss — APPROVED** [review]
LGTM. Thanks a lot for the PR!

**Pull request merged**
