### PR TITLE
Removed "restart: always" from docker-compose.yml.

### PR DESCRIPTION
**Pull request by UncleSamSwiss**
**PR Checklist:**

-   [x] Provide a meaningful description to this PR or mention which issues this fixes.
-   [x] Add tests for your change. This includes negative tests (i.e. inputs that need to fail) as well as baseline tests (i.e. how should the directory structure look like?). _not necessary_
-   [x] Run the test suite with `npm test`
-   [x] If there are baseline changes, review them and make a separate commit for them with the comment "accept baselines" if they are desired changes
-   [x] Ensure the project builds with `npm run build`
-   [x] If you added a required option, also add it to the template creation (`.github/create_templates.ts`) _not necessary_
-   [x] Add your changes to `CHANGELOG.md` (referencing this PR or the issue you fixed)

**Description:**  
This was causing issues when you have multiple projects on your PC and restart Docker and/or your PC.

### CODE REVIEW

**Comment by AlCalzone** [comment]
Do we need to use unless-stopped instead, so there is still a restart functionality?

**Comment by UncleSamSwiss** [comment]
> Do we need to use unless-stopped instead, so there is still a restart functionality?

We could try, but in the examples by Microsoft I never saw the `restart` option mentioned at all.

**Review by AlCalzone — CHANGES_REQUESTED** [review]
Ok, let's try like this. Could you please copy the PR template from https://raw.githubusercontent.com/ioBroker/create-adapter/master/.github/pull_request_template.md into your opening post and follow the checklist?
Adding tests and the required option thing should not be necessary here.

When updating the baselines, you'll probably get a bunch of version changes in package.json - that is okay.

**Review by AlCalzone — APPROVED** [review]

**Review by AlCalzone — CHANGES_REQUESTED** [review]
Sorry, one more thing: 
Could you add a migration guide for users that want to manually do this change?
See the last changelog entries.

**Comment by UncleSamSwiss** [comment]
> Could you add a migration guide for users that want to manually do this change?

Done.

**Review by AlCalzone — APPROVED** [review]

**Comment by AlCalzone** [comment]
merged in e7891a8b3c4dd1c3698adbb317b846f7fa02ba50

**Pull request closed without merging**
