### PR TITLE
Fix incorrect statement inside main.js in legacy mode (#972)

### PR DESCRIPTION
**Pull request by mcm1957**
**PR Checklist:**

-   [ ok ] Provide a meaningful description to this PR or mention which issues this fixes.
-   [ n/a ] Add tests for your change. This includes negative tests (i.e. inputs that need to fail) as well as baseline tests (i.e. how should the directory structure look like?).
-   [ *FAILS* ] Run the test suite with `npm test`
-   [ n/a ] If there are baseline changes, review them and make a separate commit for them with the comment "accept baselines" if they are desired changes
-   [ ok ] Ensure the project builds with `npm run build`
-   [ n/a ] If you added a required option, also add it to the template creation (`.github/create_templates.ts`)
-   [ n/a ] Add a detailed migration description to `docs/updates` explaining what the user needs to do when manually updating an existing project
-   [ ok ] Add your changes to `CHANGELOG.md` (referencing the migration description and this PR or the issue you fixed)

**Description:**  
I've only change one word inside the template for main.js .
npm test is not running- I assume that some setup is missing at my system.

`
>E:\GitHub\mcm1957\create-adapter>npm run build
> @iobroker/create-adapter@2.2.1 prebuild
> npm run prebuild:cleanBuildDir && npm run linkTemplates && npm run prebuild:cacheLicenses
> @iobroker/create-adapter@2.2.1 prebuild:cleanBuildDir
> rimraf ./build
>Der Befehl "rimraf" ist entweder falsch geschrieben oder
>konnte nicht gefunden werden.`

Please review code difference and accept PR if you feel OK.
OR simply discard my PR. Don't have any problem if Issue #972 is change in some other way

### CODE REVIEW

**Comment by UncleSamSwiss** [comment]
Whenever you do something in a node.js project, don't forget to do `npm install`. Then `npm run build` should work.

Your PR is currently incomplete as it doesn't contain the latest JS files (which are created during `build`) and the latest templates (which are updated during `test`).

**Review by AlCalzone — CHANGES_REQUESTED** [review]
Please run `npm install`, then repeat the failed steps.

**Comment by mcm1957** [comment]
OK - sorry, I did not really notice that this a type script file and this requires other handling than I know from java script.
I do not know how to work with typescript. 

So I cancel this PR and leave the fixe to be done by someone who knows how to work with TS. I do not want to make thinks worse.

**Comment by AlCalzone** [comment]
It is literally `npm install` and then do what what the PR checklist says:
1. `npm run build`. No error? ✅ 
2. `npm test`. This will change some baseline files so you can see if your change has the desired effect. Does it? Then commit and ✅.

The change looks good, but we need these steps to make sure the creator is always working and in a known good state.

**Comment by AlCalzone** [comment]
@mcm1957 wanna try those steps? It's really not that hard and I can help when there are issues.

**Comment by mcm1957** [comment]
ok - you talked me into doing it :-)

**Comment by AlCalzone** [comment]
FYI, step 2 will very likely result in a bunch of changed versions in package.json. That is okay - focus on the rest.

**Comment by mcm1957** [comment]
@AlCalzone 

Ok, I've cloned the repo to my system
I've done npm install

Adding (new) tests does  not seem appropiate. If really required I must quit as I do not have an idea wht to do for this.

I've now run npm run test. It works, but reports some issues I cannot figure out whether to ignore or not:

```
E:\GitHub\iobroker\create-adapter>npm run test

> @iobroker/create-adapter@2.2.1 pretest
> npm run linkTemplates


> @iobroker/create-adapter@2.2.1 linkTemplates
> node --require ts-node/register maintenance/generateTemplateIndex.ts


> @iobroker/create-adapter@2.2.1 test
> npm run test:ts && npm run test:baselines


> @iobroker/create-adapter@2.2.1 test:ts
> mocha src/**/*.test.ts



  ./core directory
    √ should not contain any imports from base directory (../)
    √ should not contain any imports from "os"
    √ should not contain any imports from "fs"
    √ should not contain any imports from "fs-extra"
    √ should not contain any imports from "path"

  actionsAndTransformers/checkMinSelections()
    √ should return true if the answers array has at least <min> entries
    √ should return an error message otherwise

  actionsAndTransformers/checkAdapterName()
    √ should not accept empty names
    √ should only accept lowercase letters, numbers, "-" and "_"
    √ should only accept names that start with a letter
    √ should only accept names that end with a letter or number
    √ should return an error if the adapter already exists
    √ should not return an error if the check is skipped
    √ should return true otherwise

  actionsAndTransformers/checkAuthorName()
    √ should not accept empty names
    √ should return true otherwise

  actionsAndTransformers/checkEmail()
    √ should only accept valid email addresses
    √ should return true for valid email addresses

  actionsAndTransformers/transformAdapterName()
You don't have to prefix the name with "ioBroker."
You don't have to prefix the name with "ioBroker."
    √ should remove leading "ioBroker." from the adapter name

  actionsAndTransformers/transformDescription()
    √ should remove leading and trailing spaces
    √ should return undefined for empty descriptions

  actionsAndTransformers/checkTitle()
    √ should not accept empty titles
    √ should return an error if the title contains iobroker or adapter
    √ should return true otherwise

  questions/questions
    √ should be an array of question objects

  questions/testCondition()
    √ should return true if a question has no condition
    √ for a "value" condition, it should return whether the answer equals the desired value
    √ for a "contains" condition, it should return whether the answer array contains the desired value
    √ for a "doesNotContain" condition, it should return whether the answer array contains the desired value
    √ should return false for invalid conditions
    √ should combine a condition array using AND

  questions/checkAnswers()
    - TODO: This is already tested by test:baselines

  questions/formatAnswers()
    - TODO: This is already tested by test:baselines

  questions/validateAnswers()
    - TODO: This is already tested by test:baselines

  createAdapter/readFile()
    √ calls fs.readFile with the absolute path
    √ passes "utf8" as the encoding when the binary option is false
    √ passes "utf8" as the encoding when the binary option is missing
    √ does not pass an encoding when the binary option is true
    √ returns the raw value from fs.readFile

  createAdapter/readFile()
    √ reads the file if it exists in the expected location
    √ reads the file from the parent directory otherwise

  LocalMigrationContext.directoryExists()
    √ should return true if the directory exists
    √ should return false if the directory doesn't exists
    √ should return false if it isn't a directory

  LocalMigrationContext.fileExists()
    √ should return true if the file exists
    √ should return false if the file doesn't exists
    √ should return false if it isn't a file

  LocalMigrationContext.hasFilesWithExtension()
    √ should return true if files exist
    √ should return false if no files exist
    √ should return false if the directory doesn't exist

  LocalMigrationContext.hasDevDependency()
    √ should return true if the dependency exists
    √ should return false if the dependency doesn't exists

  LocalMigrationContext.getMainFileContent()
    1) should return the contents of the TS file if a main JS file is found with a corresponding TS file
    √ should return the contents of the main file if a main file is found with no corresponding TS file
    √ should return an empty string if no main file is found

  LocalMigrationContext.analyzeCode()
    √ should return true the first string occurs more than the second
    2) should return false the first string occurs less often than the second

  packageVersions/getVersionSpecifier()
    √ returns the version from a package@version specifier

  packageVersions/getPackageName()
    √ returns the name from a package@version specifier

  packageVersions/fetchPackageVersion(latest)
    √ for status codes other than 200, an error is thrown
    √ for status codes other than 200, the fallback version is returned if it is passed
    √ if the status code is 200, the latest version is extracted from the response data
    √ subsequent requests should return a cached version instead of issuing another request
    √ the request object should contain an URL with the package name
    √ the request object should contain a default timeout of 5000ms
    √ if the REQUEST_TIMEOUT env variable is set, that should be the request timeout
    √ if the HTTPS_PROXY env variable is set, the proxy param should be set appropriately
    √ the proxy port should default to 443
    √ if the proxy has no valid hostname, it should not be used

  packageVersions/fetchPackageVersion(specific)
    √ for status codes other than 200, an error is thrown
    √ for status codes other than 200, the fallback version is returned if it is passed
    √ if the status code is 200, the highest matching version is extracted from the response data
    √ subsequent requests should return a cached version instead of issuing another request
    √ the request object should contain an URL with the package name

  packageVersions/fetchPackageReferenceVersion()
    √ for status codes other than 200, the requested version is returned
    √ if the status code is 200, the highest matching version is extracted from the response data

  tools/error()
    - TODO: Cannot test this because console.log should not be stubbed

  tools/indentWithTabs()
    √ should replace leading groups of 4 spaces with tabs

  tools/indentWithSpaces()
    √ should replace leading tabs with groups of 4 spaces

  tools/jsFixQuotes()
    √ should change all quotes to single quotes if that is requested
    √ should change all quotes to double quotes if that is requested
    √ should support modules (React)
    √ should support CommonJS

  tools/tsFixQuotes()
    √ should change all quotes to single quotes if that is requested (175ms)
    √ should change all quotes to double quotes if that is requested

  tools/capitalize()
    √ should capitalize the first letter in every word

  tools/kebabCaseToUpperCamelCase()
    √ should convert kebab-case to UpperCamelCase

  tools/getOwnVersion()
    √ should return the version defined in package.json

  tools/formatLicense()
    √ should replace [year] with the current year
    √ should replace [yyyy] with the current year
    √ should replace [fullname] with the author's name
    √ should replace [name of copyright owner] with the author's name
    √ should replace [email] with the author's email address

  tools/formatJsonString()
    √ should normalize the formatting of JSON strings

  tools/formatWithPrettier()
    √ should format JS code according to the Prettier rules (81ms)
    √ should format TS code according to the Prettier rules (354ms)


  90 passing (904ms)
  4 pending
  2 failing

  1) LocalMigrationContext.getMainFileContent()
       should return the contents of the TS file if a main JS file is found with a corresponding TS file:
     AssertionError: expected '' not to be empty
      at Context.<anonymous> (src\lib\localMigrationContext.test.ts:117:56)

  2) LocalMigrationContext.analyzeCode()
       should return false the first string occurs less often than the second:

      AssertionError: expected true to be false
      + expected - actual

      -true
      +false

      at Context.<anonymous> (src\lib\localMigrationContext.test.ts:165:55)

E:\GitHub\iobroker\create-adapter> ```


The failing tests seem to be:
```
  LocalMigrationContext.getMainFileContent()
    1) should return the contents of the TS file if a main JS file is found with a corresponding TS file
    √ should return the contents of the main file if a main file is found with no corresponding TS file
    √ should return an empty string if no main file is found

  LocalMigrationContext.analyzeCode()
    √ should return true the first string occurs more than the second
    2) should return false the first string occurs less often than the second
```

In addtion I think that there are NO baseline changes. B ut I do not really understand what this point refers to.

So please advise.

I'll try the build run meanwhile

**Comment by mcm1957** [comment]
Build look OK for me:

```
E:\GitHub\iobroker\create-adapter>npm run build

> @iobroker/create-adapter@2.2.1 prebuild
> npm run prebuild:cleanBuildDir && npm run linkTemplates && npm run prebuild:cacheLicenses


> @iobroker/create-adapter@2.2.1 prebuild:cleanBuildDir
> rimraf ./build


> @iobroker/create-adapter@2.2.1 linkTemplates
> node --require ts-node/register maintenance/generateTemplateIndex.ts


> @iobroker/create-adapter@2.2.1 prebuild:cacheLicenses
> node --require ts-node/register maintenance/cacheLicenses.ts

Licenses are already cached. Run this with the parameter --force to update them

> @iobroker/create-adapter@2.2.1 build
> tsc -p tsconfig.build.json


> @iobroker/create-adapter@2.2.1 postbuild
> copyfiles "templates/**/*.raw.*" build
```

**Comment by mcm1957** [comment]
Ok, I now run npm test AFTER the build.
(I think testing is better located after building but the checklist states test prior ...)

Now all tests are reported as ok

```
E:\GitHub\iobroker\create-adapter>npm test

> @iobroker/create-adapter@2.2.1 pretest
> npm run linkTemplates


> @iobroker/create-adapter@2.2.1 linkTemplates
> node --require ts-node/register maintenance/generateTemplateIndex.ts


> @iobroker/create-adapter@2.2.1 test
> npm run test:ts && npm run test:baselines


> @iobroker/create-adapter@2.2.1 test:ts
> mocha src/**/*.test.ts



  ./core directory
    √ should not contain any imports from base directory (../)
    √ should not contain any imports from "os"
    √ should not contain any imports from "fs"
    √ should not contain any imports from "fs-extra"
    √ should not contain any imports from "path"

  actionsAndTransformers/checkMinSelections()
    √ should return true if the answers array has at least <min> entries
    √ should return an error message otherwise

  actionsAndTransformers/checkAdapterName()
    √ should not accept empty names
    √ should only accept lowercase letters, numbers, "-" and "_"
    √ should only accept names that start with a letter
    √ should only accept names that end with a letter or number
    √ should return an error if the adapter already exists
    √ should not return an error if the check is skipped
    √ should return true otherwise

  actionsAndTransformers/checkAuthorName()
    √ should not accept empty names
    √ should return true otherwise

  actionsAndTransformers/checkEmail()
    √ should only accept valid email addresses
    √ should return true for valid email addresses

  actionsAndTransformers/transformAdapterName()
You don't have to prefix the name with "ioBroker."
You don't have to prefix the name with "ioBroker."
    √ should remove leading "ioBroker." from the adapter name

  actionsAndTransformers/transformDescription()
    √ should remove leading and trailing spaces
    √ should return undefined for empty descriptions

  actionsAndTransformers/checkTitle()
    √ should not accept empty titles
    √ should return an error if the title contains iobroker or adapter
    √ should return true otherwise

  questions/questions
    √ should be an array of question objects

  questions/testCondition()
    √ should return true if a question has no condition
    √ for a "value" condition, it should return whether the answer equals the desired value
    √ for a "contains" condition, it should return whether the answer array contains the desired value
    √ for a "doesNotContain" condition, it should return whether the answer array contains the desired value
    √ should return false for invalid conditions
    √ should combine a condition array using AND

  questions/checkAnswers()
    - TODO: This is already tested by test:baselines

  questions/formatAnswers()
    - TODO: This is already tested by test:baselines

  questions/validateAnswers()
    - TODO: This is already tested by test:baselines

  createAdapter/readFile()
    √ calls fs.readFile with the absolute path
    √ passes "utf8" as the encoding when the binary option is false
    √ passes "utf8" as the encoding when the binary option is missing
    √ does not pass an encoding when the binary option is true
    √ returns the raw value from fs.readFile

  createAdapter/readFile()
    √ reads the file if it exists in the expected location
    √ reads the file from the parent directory otherwise

  LocalMigrationContext.directoryExists()
    √ should return true if the directory exists
    √ should return false if the directory doesn't exists
    √ should return false if it isn't a directory

  LocalMigrationContext.fileExists()
    √ should return true if the file exists
    √ should return false if the file doesn't exists
    √ should return false if it isn't a file

  LocalMigrationContext.hasFilesWithExtension()
    √ should return true if files exist
    √ should return false if no files exist
    √ should return false if the directory doesn't exist

  LocalMigrationContext.hasDevDependency()
    √ should return true if the dependency exists
    √ should return false if the dependency doesn't exists

  LocalMigrationContext.getMainFileContent()
    √ should return the contents of the TS file if a main JS file is found with a corresponding TS file
    √ should return the contents of the main file if a main file is found with no corresponding TS file
    √ should return an empty string if no main file is found

  LocalMigrationContext.analyzeCode()
    √ should return true the first string occurs more than the second
    √ should return false the first string occurs less often than the second

  packageVersions/getVersionSpecifier()
    √ returns the version from a package@version specifier

  packageVersions/getPackageName()
    √ returns the name from a package@version specifier

  packageVersions/fetchPackageVersion(latest)
    √ for status codes other than 200, an error is thrown
    √ for status codes other than 200, the fallback version is returned if it is passed
    √ if the status code is 200, the latest version is extracted from the response data
    √ subsequent requests should return a cached version instead of issuing another request
    √ the request object should contain an URL with the package name
    √ the request object should contain a default timeout of 5000ms
    √ if the REQUEST_TIMEOUT env variable is set, that should be the request timeout
    √ if the HTTPS_PROXY env variable is set, the proxy param should be set appropriately
    √ the proxy port should default to 443
    √ if the proxy has no valid hostname, it should not be used

  packageVersions/fetchPackageVersion(specific)
    √ for status codes other than 200, an error is thrown
    √ for status codes other than 200, the fallback version is returned if it is passed
    √ if the status code is 200, the highest matching version is extracted from the response data
    √ subsequent requests should return a cached version instead of issuing another request
    √ the request object should contain an URL with the package name

  packageVersions/fetchPackageReferenceVersion()
    √ for status codes other than 200, the requested version is returned
    √ if the status code is 200, the highest matching version is extracted from the response data

  tools/error()
    - TODO: Cannot test this because console.log should not be stubbed

  tools/indentWithTabs()
    √ should replace leading groups of 4 spaces with tabs

  tools/indentWithSpaces()
    √ should replace leading tabs with groups of 4 spaces

  tools/jsFixQuotes()
    √ should change all quotes to single quotes if that is requested
    √ should change all quotes to double quotes if that is requested
    √ should support modules (React)
    √ should support CommonJS

  tools/tsFixQuotes()
    √ should change all quotes to single quotes if that is requested (177ms)
    √ should change all quotes to double quotes if that is requested

  tools/capitalize()
    √ should capitalize the first letter in every word

  tools/kebabCaseToUpperCamelCase()
    √ should convert kebab-case to UpperCamelCase

  tools/getOwnVersion()
    √ should return the version defined in package.json

  tools/formatLicense()
    √ should replace [year] with the current year
    √ should replace [yyyy] with the current year
    √ should replace [fullname] with the author's name
    √ should replace [name of copyright owner] with the author's name
    √ should replace [email] with the author's email address

  tools/formatJsonString()
    √ should normalize the formatting of JSON strings

  tools/formatWithPrettier()
    √ should format JS code according to the Prettier rules (67ms)
    √ should format TS code according to the Prettier rules (354ms)


  92 passing (869ms)
  4 pending


> @iobroker/create-adapter@2.2.1 test:baselines
> mocha test/create-adapter.test.ts



  adapter creation =>
    incomplete answer sets should fail =>
      √ only name
      √ no title
      √ no type
      √ empty title 1
      √ empty title 2
      √ invalid title 1
      √ selecting Prettier without ESLint
    generate baselines =>
      full adapter dir =>
Using dummy testing translation
        √ Adapter (w/ custom and tab), TypeScript, ESLint, Tabs, Double quotes, MIT License (7982ms)
        √ Adapter, TypeScript (ES6 class), ESLint, Tabs, Double quotes, MIT License (1257ms)
        √ Adapter, TypeScript React (3197ms)
        √ Adapter, JavaScript React (1260ms)
        √ Adapter, JavaScript, JSON UI, ESLint, Spaces, Single quotes, Apache License (1321ms)
        √ Adapter, JavaScript (ES6 class), ESLint, Spaces, Single quotes, Apache License (1265ms)
        √ Widget (1271ms)
      Single-file component tests =>
        √ Valid description (46ms)
        √ Empty description 1 (42ms)
        √ Empty description 2 (63ms)
        √ Start mode "schedule" (44ms)
        √ Adapter with type "storage"
        √ VIS with type "visualization-icons" (40ms)
        √ JS with ES2015
        √ Node.js 16 as minimum (520ms)
        √ TS(X) with single quotes (92ms)
        √ TS with Prettier (1038ms)
        √ Connection indicator (86ms)
        √ Custom adapter settings (50ms)
        √ Different keywords (46ms)
        √ Contributors (42ms)
        √ SSH protocol for git
        √ Data Source and Connection Type (38ms)
        √ VSCode devcontainer (42ms)
        √ TabReact AdminReact TS (91ms)
        √ TabReact AdminHtml JS (57ms)
        √ I18n with JSON (62ms)
        √ Release Script (1117ms)
        √ dev-server (40ms)
        √ Start mode: schedule
        √ Portal w/ GitHub
        √ No Config


  39 passing (21s)

```

**Comment by mcm1957** [comment]
You wrote: 
This will change some baseline files so you can see if your change has the desired effect. Does it? Then commit and

I do not see any changed files. Github desktop does not report anything to commit.

**Comment by AlCalzone** [comment]
Okay, thanks - I'll have to try myself. Your changes should result in a baseline update, unless we have no baseline for the legacy style.

**Comment by AlCalzone** [comment]
And you trying again is a good thing - we wouldn't have noticed that the checklist is in the wrong order otherwise ;)

**Comment by AlCalzone** [comment]
@mcm1957 your branch or fork is gone :( . I'll copy your change into a local branch and finish myself

**Comment by mcm1957** [comment]
@AlColzone
Thanks very much.

Checking the commits of your PR make clear what you mean with "baseline". I did not notice that this refers to a directory structure within test but was assume theis has something to do with git releases / git baselines or so.

And refering to lost fork. I deleted the fork as I was assuming that the changeinfo is stored in the PR anyway and my private copy was no longer needed. I think this was my error. So I did not test my change but the exsting version. Sorry for causing additionla work to you. Although I program since app 40 years I use git since 1/2 year only (I used CMS, a version control system by digital equipment later HP) and cvs only - and git is very different in usage..)

Thanks for integrating the correction and verymuch thanks for supporting me.

**Comment by AlCalzone** [comment]
All good. Next time you know 😅

**Pull request closed without merging**
