### PR TITLE
remove node 14 as minimum required version, add node 18 and node 20 as options

### PR DESCRIPTION
**Pull request by mcm1957**
**PR Checklist:**

-   [x] Provide a meaningful description to this PR or mention which issues this fixes.
-   [x] Ensure the project builds with `npm run build`
-   [x] Add tests for your change. This includes negative tests (i.e. inputs that need to fail) as well as baseline tests (i.e. how should the directory structure look like?).
-   [x] Run the test suite with `npm test`
-   [x] If there are baseline changes, review them and make a separate commit for them with the comment "accept baselines" if they are desired changes
-   [ ] If you added a required option, also add it to the template creation (`.github/create_templates.ts`)
-   [x] Add a detailed migration description to `docs/updates` explaining what the user needs to do when manually updating an existing project
-   [x] Add your changes to `CHANGELOG.md` (referencing the migration description and this PR or the issue you fixed)

**Description:**  
Node 14 is already eol and will not be supported by upcoming js-congtroller 5.x. So node 14 should not be offered as an option for minimum node version to be required.

As node 18.x is current node version and node 20.x is available too those releases should be provided as options to the question "minimum node version"

This PR solves part of issue https://github.com/ioBroker/create-adapter/issues/1032

**ATTENTION**
Please do a careful review for this PR as I am not sure whether there are any other places within the scripts which might depend on node 14 or do not acces node 18 / node 20 version strings.

### CODE REVIEW

**Comment by mcm1957** [comment]
ad 2)
```
E:\GitHub\mcm1957\create-adapter>npm run build

> @iobroker/create-adapter@2.4.0 prebuild
> npm run prebuild:cleanBuildDir && npm run linkTemplates && npm run prebuild:cacheLicenses


> @iobroker/create-adapter@2.4.0 prebuild:cleanBuildDir
> rimraf ./build


> @iobroker/create-adapter@2.4.0 linkTemplates
> node --require ts-node/register maintenance/generateTemplateIndex.ts


> @iobroker/create-adapter@2.4.0 prebuild:cacheLicenses
> node --require ts-node/register maintenance/cacheLicenses.ts

Licenses are already cached. Run this with the parameter --force to update them

> @iobroker/create-adapter@2.4.0 build
> tsc -p tsconfig.build.json


> @iobroker/create-adapter@2.4.0 postbuild
> copyfiles "templates/**/*.raw.*" build

```

Ad 4) 
```
        √ Different keywords (46ms)
        √ Contributors
        √ SSH protocol for git (38ms)
        √ Data Source and Connection Type (40ms)
        √ VSCode devcontainer (39ms)
        √ TabReact AdminReact TS (76ms)
        √ TabReact AdminHtml JS (50ms)
        √ I18n with JSON (76ms)
        √ Release Script (JS) (402ms)
        √ Release Script (TS) (59ms)
        √ dev-server (44ms)
        √ Start mode: schedule (42ms)
        √ Portal w/ GitHub (47ms)
        √ No Config
        √ JS with legacy main.js


  41 passing (17s)

```

**Comment by AlCalzone** [comment]
Ok with my changes

**Review by AlCalzone — APPROVED** [review]

**Comment by AlCalzone** [comment]
Hmm, looks like we need to upgrade TypeScript aswell

**Comment by mcm1957** [comment]
Sorry for missing typescript completly and not even noting that there must be done something.

**Comment by AlCalzone** [comment]
All good. it worked fine, until I upgraded the tsconfig base, which you seem to have missed.

**Comment by mcm1957** [comment]
> All good. it worked fine, until I upgraded the tsconfig base, which you seem to have missed.

What should I have done there so that the next time at least I (we) know thats something is missing?

I cannot program typescript (yet) and so maybe my system does not have typescritp installed correctly?
I tried to perform all steps described in an excellent way at PR template but maybe I did not read some point correctly.

**Comment by AlCalzone** [comment]
I searched for `14` in the codebase, found some more references to Node.js 14 (fallbacks), and replaced them with `16`.
That updated the `@tsconfig/nodeXX` reference in `package.json` and the `tsconfig.json` `extends` field. The local tests which you did were still ok, but on Github it actually checks if the generated adapters have any build or linter errors, which is where the problem occured.

**Comment by AlCalzone** [comment]
No worries anyways, you probably wouldn't have known to update TS from that error message:
```
 Error: node_modules/@tsconfig/node16/tsconfig.json(7,15): error TS6046: Argument for '--module' option must be: 'none', 'commonjs', 'amd', 'system', 'umd', 'es6', 'es2015', 'es2020', 'es2022', 'esnext', 'node12', 'nodenext'.
```

**Pull request merged**
