### PR TITLE
Use `require.main` to test if an adapter was started in compact mode

### PR DESCRIPTION
**Pull request by AlCalzone**
**PR Checklist:**

-   [x] Provide a meaningful description to this PR or mention which issues this fixes.
-   [ ] Add tests for your change. This includes negative tests (i.e. inputs that need to fail) as well as baseline tests (i.e. how should the directory structure look like?).
-   [x] Run the test suite with `npm test`
-   [x] If there are baseline changes, review them and make a separate commit for them with the comment "accept baselines" if they are desired changes
-   [x] Ensure the project builds with `npm run build`
-   [ ] If you added a required option, also add it to the template creation (`.github/create_templates.ts`)
-   [x] Add a detailed migration description to `docs/updates` explaining what the user needs to do when manually updating an existing project
-   [x] Add your changes to `CHANGELOG.md` (referencing the migration description and this PR or the issue you fixed)

**Description:**  
Replaced the now deprecated compact mode check using `module.parent` with one that uses `require.main`

### CODE REVIEW

**Comment by AlCalzone** [comment]
Blocked by https://github.com/microsoft/TypeScript/issues/41764 :(

**Comment by AlCalzone** [comment]
This will be solved in TypeScript 4.2, so let's wait for that.

**Comment by UncleSamSwiss** [comment]
What are we waiting for? ;-) jk
https://devblogs.microsoft.com/typescript/announcing-typescript-4-2/

**Comment by AlCalzone** [comment]
This works now :)

**Pull request merged**
