### PR TITLE
Update github tests to use node 16.x/18.x/20.x

### LINKED ISSUE #1032: Node updates - remove node 14, add node 20
I would suggest to remove support for node 14 and to add support for node 20:

-) at selection of minimum node required (maybe do not yet support node 20 only)
-) at generated test environment

### PR DESCRIPTION
**Pull request by mcm1957**
**PR Checklist:**

-   [x] Provide a meaningful description to this PR or mention which issues this fixes.
-   [x] Ensure the project builds with `npm run build`
-   [ ] Add tests for your change. This includes negative tests (i.e. inputs that need to fail) as well as baseline tests (i.e. how should the directory structure look like?).
-   [x] Run the test suite with `npm test`
-   [x] If there are baseline changes, review them and make a separate commit for them with the comment "accept baselines" if they are desired changes
-   [ ] If you added a required option, also add it to the template creation (`.github/create_templates.ts`)
-   [x] Add a detailed migration description to `docs/updates` explaining what the user needs to do when manually updating an existing project
-   [x] Add your changes to `CHANGELOG.md` (referencing the migration description and this PR or the issue you fixed)

**Description:**  
As js-controller 5 will no longer support node 14 and node 14 already reached end of life it should no longer be configured at github based testmatrix per default.

Singe node tests (as eslint) should use node 18.x as node 16.x will reach eol end of 2023.

Node 20.x shhould be added to default testmatrix as there is no known reason why a new adapter should nozt be tested (nad be compatible) to node 20.x

So the following changes are performed:

-) single node tests using 'latest' release now use node 18.x
-) test matrix for standard github tests is set to [16.x,18.x,20.x]

fixes: #1032

### CODE REVIEW

**Comment by mcm1957** [comment]
ad 2) 
```
E:\GitHub\mcm1957\create-adapter>npm run build

> @iobroker/create-adapter@2.4.0 prebuild
> npm run prebuild:cleanBuildDir && npm run linkTemplates && npm run prebuild:cacheLicenses


> @iobroker/create-adapter@2.4.0 prebuild:cleanBuildDir
> rimraf ./build


> @iobroker/create-adapter@2.4.0 linkTemplates
> node --require ts-node/register maintenance/generateTemplateIndex.ts


> @iobroker/create-adapter@2.4.0 prebuild:cacheLicenses
> node --require ts-node/register maintenance/cacheLicenses.ts

Licenses are already cached. Run this with the parameter --force to update them

> @iobroker/create-adapter@2.4.0 build
> tsc -p tsconfig.build.json


> @iobroker/create-adapter@2.4.0 postbuild
> copyfiles "templates/**/*.raw.*" build
```

ad 4)
```
        √ Connection indicator (66ms)
        √ Custom adapter settings (47ms)
        √ Different keywords (45ms)
        √ Contributors (41ms)
        √ SSH protocol for git (41ms)
        √ Data Source and Connection Type (42ms)
        √ VSCode devcontainer
        √ TabReact AdminReact TS (89ms)
        √ TabReact AdminHtml JS (49ms)
        √ I18n with JSON (61ms)
        √ Release Script (JS) (368ms)
        √ Release Script (TS)
        √ dev-server (48ms)
        √ Start mode: schedule (47ms)
        √ Portal w/ GitHub (42ms)
        √ No Config
        √ JS with legacy main.js


  41 passing (18s)

```

**Comment by mcm1957** [comment]
ad 3)
If dedicated tests are required, please let me know how to provide those

**Comment by mcm1957** [comment]
@AlCalzone 
Sorry wenn ich dränge / nachfrage
Da nun github tests mit Node 14 failen, kannst du dir bitte dir PRs ansehen - zumindest diesen hier der nur die Testconfig anpasst ?

**Review by AlCalzone — APPROVED** [review]
I've merged the changelog with the one from the other PR

**Pull request merged**
